### ISSUE TITLE
Shutting down testing openldap server should not happen in tearDown

### ISSUE THREAD

**Issue by domenkozar** [conestack/node.ext.ldap#1] opened 2012-03-16 23:35 UTC
Background:

tearDown method will only be called after each test is finished. If test raised any exception (such as KeyboardError), tearDown will not be called. Next time developer runs tests, openldap will already contain data and setUp will fail.

**Comment by rnixx** [comment] 2022-03-17 16:24
Cannot reproduce any more. When interrupting the test, the LDAP server instance is gone, and so the data. Closing this.

**Closed as completed by rnixx** 2022-03-17 16:24 UTC
Labels: bug
